Pipeline: Combines preprocessing and model training into a single workflow.
ColumnTransformer: Applies different preprocessing techniques to different columns in a dataset.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')
from IPython.display import display
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_regression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

from sklearn.ensemble import VotingRegressor

In [2]:
df=sns.load_dataset('tips') #given tips on restaurant
display(df.head(5))
display(df.info())
display(df.isnull().sum())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

None

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [3]:
# our targer variable is time . like we have to predict the visiting time 
print(df['time'].unique())
from sklearn.preprocessing import LabelEncoder
l_enc=LabelEncoder()
df['time']=l_enc.fit_transform(df['time'])
print(df['time'].unique())
display(df.head(3))

# Splitting into x and y
x=df.drop('time',axis=1)
y=df['time']
display(x.head(3))
display(y.head(3))

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']
[0 1]

   total_bill   tip     sex smoker  day  time  size
0       16.99  1.01  Female     No  Sun     0     2
1       10.34  1.66    Male     No  Sun     0     3
2       21.01  3.50    Male     No  Sun     0     3

   total_bill   tip     sex smoker  day  size
0       16.99  1.01  Female     No  Sun     2
1       10.34  1.66    Male     No  Sun     3
2       21.01  3.50    Male     No  Sun     3

0    0
1    0
2    0
Name: time, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
# even if there is no null or missing value but for understanding the process we will do this.

from sklearn.impute import SimpleImputer # for missing value
from sklearn.preprocessing import OneHotEncoder # for encoding
from sklearn.preprocessing import StandardScaler # for scaling 
from sklearn.pipeline import Pipeline # to apply multiple preprocessing
from sklearn.compose import ColumnTransformer # group all the pipeline step for each column
display(df.sample(1))
cat_cols=['sex','smoker','day']
num_cols=['total_bill','tip','size']

# Feature engineering automation using pipeline and column transformer
num_pipeline=Pipeline(steps=[('imputation',SimpleImputer(strategy='median')),
                              ('Scaling',StandardScaler())])
cat_pipeline=Pipeline(steps=[('imputation',SimpleImputer(strategy='most_frequent')),
                              ('encoding',OneHotEncoder())])
pre_processor=ColumnTransformer([('num_pipeline',num_pipeline,num_cols),('cat_pipeline',cat_pipeline,cat_cols)])
# prepare the data
x_train=pre_processor.fit_transform(x_train)
x_test=pre_processor.transform(x_test)

models={
    'support vector classifier':SVC(),
    'Desion tree classifier':DecisionTreeClassifier(),
    'Logistic regression': LogisticRegression()
}
models

for i in range(len(models)):
    print(list(models.values())[i])
def model_train_eval(x_train,x_test,y_train,y_test,models):
    evaluation={}
    for i in range(len(models)):
        model=list(models.values())[i]
        model.fit(x_train,y_train)
        y_pred=model.predict(x_test)
        acc_model=accuracy_score(y_pred,y_test)
        evaluation[list(models.keys())[i]]=acc_model
    return evaluation
model_train_eval(x_train,x_test,y_train,y_test,models)

     total_bill  tip     sex smoker   day  time  size
133       12.26  2.0  Female     No  Thur     1     2

SVC()
DecisionTreeClassifier()
LogisticRegression()

{'support vector classifier': 0.9672131147540983,
 'Desion tree classifier': 0.9508196721311475,
 'Logistic regression': 1.0}