### Regularization:
it is risk mitigation technique used in machine learning to prevent overfitting by penalizing unnecessary complexity in model.
regularization put discipline in the model
### Ridge:
keep all features but reduce their powers
used in pricing model
### Lasso:
remove all useless feature completely
### Elastic net:
remove less and control the rest

In [1]:
# Importing essential lib
# we will use mpg dataset
""" 1miles=1.6 km
    1 gallom=3.7 ltr
 """
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings('ignore')
from IPython.display import display
from sklearn.model_selection import GridSearchCV , RandomizedSearchCV

In [2]:
df=sns.load_dataset('mpg')
display(df.head(5))
df.drop('name', axis=1,inplace=True)
display(df.info())
# to check null value in any column
display(df.isna().sum())

# filling the null value with median
df['horsepower']=df['horsepower'].fillna(df['horsepower'].median())
#display(df.isna().sum())
display(df['origin'].value_counts())
display(df.origin.unique())

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

None

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

array(['usa', 'japan', 'europe'], dtype=object)

In [3]:
# Data encoding
df['origin']=df['origin'].str.strip()
df['origin']=df['origin'].map({"usa":1,"japan":2,"europe":3})
display(df.head(5))
display(df['origin'].unique())
display(df['origin'].dtype)

# Spliting the data
x=df.drop('mpg',axis=1)
y=df['mpg']
#display(x.head(5))

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,1
1,15.0,8,350.0,165.0,3693,11.5,70,1
2,18.0,8,318.0,150.0,3436,11.0,70,1
3,16.0,8,304.0,150.0,3433,12.0,70,1
4,17.0,8,302.0,140.0,3449,10.5,70,1

array([1, 2, 3])

dtype('int64')

In [4]:
# Train Test Split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25 ,random_state=42)
display(x_train.head(5))
display(x_train.shape)
display(x_test.shape)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
245,4,98.0,66.0,1800,14.4,78,1
110,4,108.0,94.0,2379,16.5,73,2
16,6,199.0,97.0,2774,15.5,70,1
66,8,304.0,150.0,3672,11.5,72,1
153,6,250.0,105.0,3459,16.0,75,1

(298, 7)

(100, 7)

In [5]:
# r2 for the model
r2_score_of_model=r2_score(y_test,y_pred)
display(f"r2_score_of_model is {round(r2_score_of_model*100,4)} %")

'r2_score_of_model is 83.7244 %'

In [ ]:
# Lasso Regression: L1 Regularization
from sklearn.linear_model import Lasso
lasso_regression=Lasso(alpha=1)
lasso_regression.fit(x_train,y_train)
#enumerate() is a built-in Python function that returns both the index and the value of each element while iterating over an iterable.
for i ,col_name in enumerate(x_train.columns):
    print(f"the coefficient for {col_name} is {lasso_regression.coef_[i]}")
y_pred_lasso=lasso_regression.predict(x_test)
r2_score_lasso=r2_score(y_test,y_pred_lasso)
print(f"model performance under lasso {round(r2_score_lasso*100,4)} % ")
# it has set 3 columns as 0. the accuracy may down by few % but model dont have to deal with atleast 3 irrelevent column so actually it is good for the model.

the coefficient for cylinders is 0.0
the coefficient for displacement is -0.0029750579684931513
the coefficient for horsepower is -0.002236741927543011
the coefficient for weight is -0.0064813895537840175
the coefficient for acceleration is 0.0
the coefficient for model_year is 0.7042913638821322
the coefficient for origin is 0.0
model performance under lasso 83.2284 %

In [7]:
# Ridge Regression: L2 Regularization
from sklearn.linear_model import Ridge
ridge_regression=Ridge(alpha=5) # alpha is the regularization strength . it controls how much penality is applied to the large co-efficient
ridge_regression.fit(x_train,y_train)
for i ,col_name in enumerate(x_train.columns):
    print(f"the coefficient for {col_name} is {ridge_regression.coef_[i]}")
ridge_pred=ridge_regression.predict(x_test)
r2_score_of_model=r2_score(ridge_pred,y_test)
display(f"model performance under ridge is {round(r2_score_of_model*100,4)} %")

the coefficient for cylinders is -0.014348805764804318
the coefficient for displacement is 0.01164531803393921
the coefficient for horsepower is -0.0036803356614291786
the coefficient for weight is -0.007103019446485048
the coefficient for acceleration is 0.07784290366065455
the coefficient for model_year is 0.8320701682094672
the coefficient for origin is 1.426344965396796

'model performance under ridge is 83.9864 %'

In [8]:
# Elastic Net: 
from sklearn.linear_model import ElasticNet
elastic_net=ElasticNet(alpha=1,l1_ratio=0.25) # means 25% lasso and 75 ridge
elastic_net.fit(x_train,y_train)
y_pred_elastic_net=elastic_net.predict(x_test)
for i ,col_name in enumerate(x_train.columns):
    print(f"the coefficient for {col_name} is {elastic_net.coef_[i]}")
r2_score_elastic_net=r2_score(y_test,y_pred_elastic_net)
print(f"model performance under elastic net {round(r2_score_elastic_net*100,4)} % ")

the coefficient for cylinders is 0.0
the coefficient for displacement is -0.0006736771395752426
the coefficient for horsepower is -0.005030780181430014
the coefficient for weight is -0.006494458775799507
the coefficient for acceleration is 0.0
the coefficient for model_year is 0.7259081193124405
the coefficient for origin is 0.23987160226773477
model performance under elastic net 83.4613 %

In [9]:
# Cross Validation and Hyperparameter tuning: 
""" Cross Validation cheks performance stability
    Hyperparameter tuning finds best settings
"""
# Parameter of GridSearchCV 
# estimator: which model would be used for tuning
# param_grid: Hyperparameter ki dict , it tells which value should be try
# scoring : model ko evaluate krne ka metric
# cv : number of folds like kitne part me devide hoga data. like kitni bar model train hoga
# verbose: progress print krne ke liye 
lasso= Lasso()
param_grid={'alpha': [0.001,0.01,0.1,1,10,100]}
grid_search=GridSearchCV(estimator=lasso,param_grid=param_grid,cv=5,scoring='r2',verbose=2)
grid_search.fit(x_train,y_train)
grid_search.best_params_
y_pred_grid=grid_search.predict(x_test)
r2_score_grid=r2_score(y_test,y_pred_grid)
display(f" model performance under gridsearchcv {round(r2_score_grid*100,4)} % ")

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

' model performance under gridsearchcv 83.7712 % '

In [12]:
param_distribution={'alpha':[0.01,0.1,1,10,100]}
randmised=RandomizedSearchCV(estimator=lasso,param_distributions=param_distribution,n_iter=5,cv=6,scoring='r2',verbose=2)
randmised.fit(x_train,y_train)
y_pred_randomised=randmised.predict(x_test)
r2_score_randomised=r2_score(y_test,y_pred_randomised)
display(f"model performance under randomisedsearchcv {round(r2_score_randomised*100,4)} % ")
randmised.best_params_

Fitting 6 folds for each of 5 candidates, totalling 30 fits
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

'model performance under randomisedsearchcv 83.7712 % '

{'alpha': 0.1}

In [18]:
# Elastic Net GridsearchCV
model=ElasticNet()
param_grid={'alpha':[0.001,0.01,0.1,1,10,100],'l1_ratio':[0.1,0.2,0.3,0.4,0.5]}
elastic_grid=GridSearchCV(estimator=model,param_grid=param_grid,scoring='r2',cv=5,verbose=2)
elastic_grid.fit(x_train,y_train)
y_pred_elastic_grid=elastic_grid.predict(x_test)
r2_score_el_grid=r2_score(y_test,y_pred_elastic_grid)
print(f"model performance under elastic net using GridSearchCV {round(r2_score_el_grid*100,4)} % ")
print(elastic_grid.best_params_)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.2; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.2; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.2; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.2; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.2; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.3; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.3; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.2; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.2; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.2; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.2; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.2; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.3; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.2; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.2; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.2; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.2; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.2; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.3; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.2; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.3; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.5; total time=   0.0s
model performance under elastic net using GridSearchCV 83.7861 %
{'alpha': 0.1, 'l1_ratio': 0.5}